# Generated by Django 5.1.1 on 2024-10-30 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_poster_img'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='categories.event'),
            preserve_default=False,
        ),
    ]
