# Generated by Django 5.1.1 on 2024-09-18 20:13

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3, message='Category name needs to be at least 3 characters long.')])),
                ('short_description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(10, message="Category's short description needs to be at least 10 characters long.")])),
                ('long_description', models.CharField(max_length=1100, validators=[django.core.validators.MinLengthValidator(70, message="Category's long description needs to be at least 70 characters long.")])),
                ('active_members', models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
