# Generated by Django 5.1.1 on 2024-09-29 11:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3, message='Category name needs to be at least 3 characters long.')])),
                ('short_description', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(10, message="Category's short description needs to be at least 10 characters long.")])),
                ('long_description', models.CharField(max_length=1100, validators=[django.core.validators.MinLengthValidator(70, message="Category's long description needs to be at least 70 characters long.")])),
                ('active_members', models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(2, message='Title needs to be at lest 2 characters long.')])),
                ('details', models.CharField(max_length=10000, validators=[django.core.validators.MinLengthValidator(150, message='Details about the event need to be at least 150 characters long.')])),
                ('city', models.CharField(default='Haskovo', max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='City needs to be at least 2 characters long.')])),
                ('location', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, message='Exact location needs to be at least 10 characters long.')])),
                ('time', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
