# Generated by Django 5.1.1 on 2024-09-24 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(2, message='Title needs to be at lest 2 characters long.')])),
                ('details', models.CharField(max_length=10000, validators=[django.core.validators.MinLengthValidator(150, message='Details about the event need to be at least 150 characters long.')])),
                ('location', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='Exact location needs to be at least 10 characters long.')])),
                ('time', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
        ),
    ]
