# Generated by Django 5.1.1 on 2024-09-29 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='City needs to be at least 2 characters long.')]),
        ),
    ]
