# Generated by Django 5.1.1 on 2024-10-26 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_category_active_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='poster_img',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
