# Generated by Django 5.1.1 on 2024-10-26 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_poster_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='poster_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
