# Generated by Django 5.1.1 on 2024-09-30 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_event_category_alter_event_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='long_description',
            field=models.CharField(max_length=1100, validators=[django.core.validators.MinLengthValidator(450, message="Category's long description needs to be at least 70 characters long.")]),
        ),
    ]
