# Generated by Django 5.1.1 on 2024-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_alter_category_poster_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online_meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
