# Generated by Django 5.1.1 on 2024-09-26 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_event_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, message='Exact location needs to be at least 10 characters long.')]),
        ),
    ]
