# Generated by Django 5.1.1 on 2024-11-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_event_online_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='online',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
