# Generated by Django 5.1.1 on 2024-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_event_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='online_meeting_link',
            field=models.URLField(),
        ),
    ]
