# Generated by Django 5.1.1 on 2024-10-10 14:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_event_poster_image_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
