# Generated by Django 5.1.1 on 2024-11-26 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_event_city_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, message='City needs to be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(10, message='Exact location needs to be at least 10 characters long.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='online_meeting_link',
            field=models.URLField(),
        ),
    ]
