# Generated by Django 5.1.1 on 2024-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_alter_event_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
