# Generated by Django 5.1.1 on 2024-10-10 19:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_alter_event_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
