# Generated by Django 5.1.1 on 2024-11-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0010_categoryimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_emergency',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
