# Generated by Django 5.1.1 on 2024-10-25 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0011_alter_event_poster_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(max_length=10000, validators=[django.core.validators.MinLengthValidator(1000, message='Details about the event need to be at least 150 characters long.')]),
        ),
    ]
