# Generated by Django 5.1.1 on 2024-09-15 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_appuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2, message='First name needs to be at least 2 characters long.')])),
                ('last_name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2, message='Last name needs to be at least 2 characters long.')])),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Phone number needs to be exact 10 characters long.')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
