# Generated by Django 5.1.1 on 2024-11-18 22:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dzfgtuvut/image/upload/v1731968047/zqknwmkjcvtl1nes9vnh.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
