# Generated by Django 5.1.1 on 2024-09-15 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=800, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Bio needs to be at least 10 characters long.')]),
        ),
    ]
