# Generated by Django 5.1.1 on 2024-09-19 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=800, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Bio needs to be at least 10 characters long.')]),
        ),
    ]
