# Generated by Django 5.1.1 on 2024-12-08 18:14

import VolunteerAct.app_users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2, message='First name needs to be at least 2 characters long.'), VolunteerAct.app_users.validators.first_name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Last name needs to be at least 2 characters long.'), VolunteerAct.app_users.validators.last_name_validator]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Phone number needs to be exact 10 characters long.'), VolunteerAct.app_users.validators.phone_number_validator]),
        ),
    ]
