# Generated by Django 5.1.1 on 2025-02-23 09:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dd9sshsar/image/upload/v1739819088/xsr0ppnp8sblakuoanix.png', max_length=255, null=True),
        ),
    ]
